version: '3.3'
name: movie-api-e2e-test
services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
    ports:
      - "3000:3000"
    environment:
      WAIT_HOSTS: db:3306
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: movie-api
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie-api