version: '3'
name: movie-api
services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie-api